const tagInfoList = [
    {
        title: '物质',
        tagList: [
            {
                tag:'潮牌', 
                tagId:0
            },
            {
                tag:'吃喝攻略', 
                tagId:1
            },
            {
                tag:'理财', 
                tagId:2
            },
            {
                tag:'家具好物', 
                tagId:3
            },
            {
                tag:'智能生活', 
                tagId:4
            },
            {
                tag:'礼物', 
                tagId:5
            },
            {
                tag:'球鞋', 
                tagId:6
            }
        ]
    },
    {
        title: '兴趣',
        tagList: [
            {
                tag:'日韩剧', 
                tagId:0
            },
            {
                tag:'游戏', 
                tagId:1
            },
            {
                tag:'古典音乐', 
                tagId:2
            },
            {
                tag:'手账', 
                tagId:3
            },
            {
                tag:'电影', 
                tagId:4
            },
            {
                tag:'健身', 
                tagId:5
            },
            {
                tag:'咖啡', 
                tagId:6
            }, 
            {
                tag:'手机摄影', 
                tagId:7
            }
        ]
    },
    {
        title: '世界',
        tagList: [
            {
                tag:'菜市场', 
                tagId:0
            },
            {
                tag:'环球旅行', 
                tagId:1
            },
            {
                tag:'艺术展览', 
                tagId:2
            },
            {
                tag:'酒店民宿', 
                tagId:3
            },
            {
                tag:'日本旅行', 
                tagId:4
            },
            {
                tag:'出行锦囊', 
                tagId:5
            },
            {
                tag:'打折机票', 
                tagId:6
            }
        ]
    },
    {
        title: '新事',
        tagList: [
            {
                tag:'轻芒杂志', 
                tagId:0
            },
            {
                tag:'设计生活', 
                tagId:1
            },
            {
                tag:'轻芒封面文章', 
                tagId:2
            },
            {
                tag:'世界大事', 
                tagId:3
            },
            {
                tag:'小新闻', 
                tagId:4
            },
            {
                tag:'技巧', 
                tagId:5
            },
            {
                tag:'古文', 
                tagId:6
            }
        ]
    }
]

export {tagInfoList}